apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  # Add repositories
  repositories: |
    - url: https://github.com/kims/ssp-argocd.git
      name: app
      type: git
  url: "localhost:8080"
  # Create user accounts
  accounts.dev1: apiKey, login
  accounts.dev2: apiKey, login
