apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    p, role:admin, *, *, *, allow

    p, role:dev1-role, applications, *, app1-project/*, allow
    p, role:dev1-role, repositories, get, *, allow
    p, role:dev1-role, clusters, get, *, allow
    p, role:dev1-role, projects, get, app1-project, allow
    
    p, role:dev2-role, applications, *, app2-project/*, allow
    p, role:dev2-role, repositories, get, *, allow
    p, role:dev2-role, clusters, get, *, allow
    p, role:dev2-role, projects, get, app2-project, allow
    
    g, dev1, role:dev1-role
    g, dev2, role:dev2-role
    g, admin, role:admin
    
  policy.default: role:none

