apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
type: Opaque
stringData:
  # Bcrypt hashed passwords (these are "password123" - CHANGE THESE!)
  # Generate with: argocd account bcrypt --password <password>
  accounts.dev1.password: "$2a$10$rRyBsGSHK6.uc8fntPwVIuLVHgsAhAX7TcdrqW/XGaaZkMWdyE.6i"
  accounts.dev2.password: "$2a$10$rRyBsGSHK6.uc8fntPwVIuLVHgsAhAX7TcdrqW/XGaaZkMWdyE.6i"
