# ssp-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: self-service-password
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssp
  template:
    metadata:
      labels:
        app: ssp
    spec:
      containers:
      - name: ssp-container
        image: ltbproject/self-service-password:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: ssp-config-volume
          mountPath: /var/www/conf/config.inc.local.php
          subPath: config.inc.local.php
      volumes:
      - name: ssp-config-volume
        configMap:
          name: ssp-config # References the ConfigMap created earlier
