apiVersion: v1
kind: Secret
metadata:
    name: my-secret
    namespace: app1
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:xdLJ5xki3AO0VdlfNQ==,iv:ByWt++ZQxMMk5ATd16B5t3EOC7koo3UQFn0J32VqLqw=,tag://LcfTkkuhmD4aE8kwD4Sg==,type:str]
sops:
    lastmodified: "2025-10-29T16:33:12Z"
    mac: ENC[AES256_GCM,data:NheAaxBg2vUO6ePXKMt7o9sPM9juRPoFQU5t/o1xN1CbJQu+EV14pnjxV8iOCmCXO0PRQgAmwbsXrnBgCjh47ZF+pKH8vqkVKRuQ5GaTMd+7jUMhrwSrfjGMWwfJ/5iTdNpzc/mksfIdkDiuDTH3VfizAbFRXQMnZp13WSm+bC8=,iv:uR7LUCRd+zfRYFqR4hUaH6qSM6hZp7e/h1k4CmOI1V0=,tag:0GsvuvjsI4elDS1H3zj8mA==,type:str]
    pgp:
        - created_at: "2025-10-29T16:33:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA/Z/iXtHeIA/AQwAyYz8YTg1ay+iDADdSZtDqhArOsDz+pJNrgSuPCY6doxd
            VNLOjv15W5prGjN8uDbhTj2HpavPIjw4xgykJpS1iPHInG36WukY8WIf/Y1v3PXJ
            bfOYuAb+IkBzGt1PB9ElrtQDlmJzLL+1hsIPOGR4mKmbSQ4+/rFZwgBtQNkFAAoj
            bfpLEgYyjz2zy79T8DWTdvroXVkRiwfiRDBwF6ul5BoVyaIpDfogXqSUTNMpyvSW
            3fCrkAbUzsVhgz0ayXq0Xtk++RQU0XcrjvpCMp0VcLlnoDF62GmbxBhf+admGS0C
            5ilAG3r5h8+DFWJi7Dh3gSQ2aSusYAH8M/Az4b0syavW4rg+M4c6oDfYkqS1uUj+
            wpcAoanf6wwFIdpXbJxeVdJ0ON4dVB5E1EmVCgkcUtggm+xqLRGYTgOxKQSvHWeY
            MCMvzN6hOlmYyoqS9Jkm0FwI9bx7gmiyUEkwqcjSFVGQEQ588wXFMDq+H9GCUboK
            O2RLz6x3qOul+JmY4WQJ1GYBCQIQikdCHzZs9e9WYLaswnRvXPBmkcGfU3kWPMez
            ljFs10dljkuWkCIdlRMTx+iJWgMlgo4do285y9rjr8+gJ9uhGfKAwrHoDDq6iTpi
            pTIJOqP03SxNIIIOsZmGUKkypgszxc0=
            =mWUm
            -----END PGP MESSAGE-----
          fp: 750C1B9FED7B317F9F59015ABFDBF617C8824510
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
