---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dev1-db-pass
  namespace: dev1
spec:
  encryptedData:
    password: AgBEXiCR8tTWugKU53Z0LOOWPctLtczUNnYswqaOzxsK7eh8DNYkp0tCsnYQLyE8OJmGpL1igma7NDQSEMCVDdUjcFt6fzDoVP5/q+8wDiAd2uE57tzzrLaS5VmWfQTJzBTihhtFHIksf/J/DbsulxdOK3KGzm6L2L8wSq/609AeyodaUebQ1NF2TvCxmpmMDHmCD1d45IdjDRKVWe3t9ZITAmo/3bvbAq63jUo0CauM2KZ59HCUdq0ck32fY5DYVqAojcmSOJR4e5tuXr76La/q6vvYI/yBKXahDV4X1PmWELyfUfSaQWUsDByZawwGJxHQoCpdCndhsYgINI+RX7nxDQBlrt5IE1KEk2EfawqatcAkdObtmZ40+lGI1qrZc8alwRwrZu8dXZ/6B+PmgxHgOoCRk1wq7Qr7XbHKh+DCvlGKA+YkZRCxFl2L/BV/ubfV7QLcqcv0NcrUixgUKAcCbQvmiyEhaYv00A1b4phMeIxCKl+3xOYXxw7lUhooI+nncHEsmFUK0wXK4T0qR4QLXpeqgmDz1gQjLzk83VNZbpYtFIWjDC1d/1T/0cMvtpCSL5OmnROPKZuvhsrzDtG4O9Pf/1oqn226I45bYP8JHMQlv5F5Kws0+TZHKudY/ji2K2AVQE3f4P865tdnimSAwUM8X5rjpbM3/H+BYQl+IX2xgKP6HxqINIRw47FHiNcV+/lmu8I=
    username: AgCG/FTEbclO9W+8ZjDDL1uCI6FEOa7pU/FwlTWOOXPGfB2gmjpxfgZOcAMvKMfHKTBkUZXsr9cIdHeffNMRmvO9TCFKvjOI/UipqBtfM3H/N1CablsfJSZesGvLvEbRcbCTUSGAipfL/nOr5JLTctnASuIuHAcxbeLuGXY6ErlS4tm9ctqWVJtsylsgSE0nSpoyz4hEMGwrPbfyF78by5w9Xw4JJrqV4K4NPCcHsfPyUh+d7J574xGSt+gI+XEWhQY0XW4tyanjJeBlEx64h9+3ZJReDVd5SMv5mxwMOa7OW2otlmY4OD7RaIneisakbZTIoTPTYB0eom8uEuJ9yBMlE5s3I+IciTEZSCB0s5Dy+XLTGogoRicSpDC0fVXD1IOSR7WZQF2/iJiEzdm3J96DmAu3CfWwAjx3AsA3ytWllzmdqMYU6yKMbVwYHriamdSekZnAOuo3e2qAHMNSptC6zZIEdg/HjF3eYF+zz+wzyrY5jYp6rws8G+FEvCxKxNbCd4Ytx6+CbDGI93R8P5KYBXm0vjKzkBTJWsbECHcnys82XcLTqQZQvigdTTnc9bayHgzynF10PcwA6Verim/ohnhuZUHsWkECkeO7IhyD9eMZMPU0xzSl5oTwN9Nl3MgHEdq5+bTxlWyNi4NiRPe75aVjpJ/Ac51LLdQ83un/dEro1s5egy4QPcEiiEQGTGi7Dwj3
  template:
    metadata:
      name: dev1-db-pass
      namespace: dev1
